server:
  port: 44316
spring:
  profiles:
    active: core
  application:
    name: finance
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 12
    lettuce:
      pool:
        max-active: 300
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wk_open_finance?characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&serverTimezone=Asia/Shanghai&useAffectedRows=true&allowPublicKeyRetrieval=true&sessionVariables=sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'
    username: root
    password: password
  elasticsearch:
    uris: 127.0.0.1:9200
jetcache:
  statIntervalMinutes: 0
  areaInCacheName: false
  local:
    default:
      type: caffeine
      limit: 1000
      keyConvertor: fastjson
      expireAfterWriteInMillis: 100000
  remote:
    default:
      type: redis.lettuce
      keyConvertor: fastjson
      #mode: cluster
      # 不需要password的redis连接为 redis://127.0.0.1:6379/
      uri: redis://123456@127.0.0.1:6379/
wukong:
  common:
    upload:
      type: local
      region: D:/wukong
      domain: /commonFile/download
      bucket-name: D:/wukong
